Set up

In [2]:
import numpy as np
import torch

In [3]:
SEED = 1234

In [ ]:
# set seed for reproducibility
np.random.seed(seed=SEED)
torch.manual_seed(seed=SEED)

Basics

In [8]:
# creating a random tensor
x = torch.randn(2, 3)
print (
    f"Type: {x.type()}\n"
    f"Size: {x.shape}\n"
    f"Values: \n{x}"
)

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[-0.0098, -1.4473, -0.2039],
        [ 0.8738, -0.6816,  0.6339]])


In [10]:
# zero and ones tensor
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
# list to tensor
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print (
    f"Shape: {x.shape}\n"
    f"Values: \n{x}"
)

Shape: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [15]:
# Numpy array to tensor
x = torch.Tensor(np.random.randn(2, 3))
print (
    f"Shape: {x.shape}\n"
    f"Values: \n{x}"
)

Shape: torch.Size([2, 3])
Values: 
tensor([[ 0.8596, -0.6365,  0.0157],
        [-2.2427,  1.1500,  0.9919]])


In [19]:
# Changing tensor type
x = torch.Tensor(3, 4)
print (
    f"Type: {x.type()}\n"
    f"Value: \n{x}"
    )
x = x.long()
print (
    f"Type: {x.type()}\n"
    f"Value: \n{x}"
    )


Type: torch.FloatTensor
Value: 
tensor([[4.5919e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.0694e+26, 4.5912e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.1351e-43, 0.0000e+00]])
Type: torch.LongTensor
Value: 
tensor([[                   0,                    0,                    0,
                            0],
        [-9223372036854775808,                    0,                    0,
                            0],
        [                   0,                    0,                    0,
                            0]])


Operations

In [21]:
# Addition
x = torch.randn(2, 3)
print(f"x: \n{x}")
y = torch.randn(2, 3)
print(f"y: \n{y}")
z = x + y
print(
    f"x + y Size: {z.shape}\n"
    f"Sum: \n {z}"
)

x: 
tensor([[ 0.4501,  0.2709, -0.8087],
        [-0.0217, -1.0413,  0.0702]])
y: 
tensor([[ 0.5797, -0.0599,  0.1816],
        [-0.6797, -0.2567, -1.8189]])
x + y Size: torch.Size([2, 3])
Sum: 
 tensor([[ 1.0297,  0.2110, -0.6272],
        [-0.7014, -1.2980, -1.7486]])


In [22]:
# dot product
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([2, 2])
Values: 
tensor([[-0.5756, -1.1599],
        [ 1.8682, -1.2855]])


In [25]:
# transpose
x = torch.randn(2, 3)
print(f"Size: {x.shape}")
print(f"Values: \n{x}")
y = torch.t(x)
print(f"Size: {y.shape}")
print(f"Values: \n{y}")

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.8246, -0.5723, -0.4876],
        [ 0.1944, -1.0481, -0.0741]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.8246,  0.1944],
        [-0.5723, -1.0481],
        [-0.4876, -0.0741]])


In [26]:
# Reshape
x = torch.randn(2, 3)
print(f"x: \n{x}")
z = x.view(3, 2)
print(f"Size: {z.shape}")
print(f"Reshaped: \n{z}")

x: 
tensor([[-0.3449, -1.5447,  0.0685],
        [-1.5104, -1.1706,  0.2259]])
Size: torch.Size([3, 2])
Reshaped: 
tensor([[-0.3449, -1.5447],
        [ 0.0685, -1.5104],
        [-1.1706,  0.2259]])


In [31]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [34]:
# Dimentional operation
x = torch.randn(2, 3)
print(f"x Values: \n{x}")
y = torch.sum(x, dim=0) # add each rows value to every column
print(f"y Values: \n{y}")
z = torch.sum(x, dim=1) # add each columns's value for every row
print(f"z Values: \n{z}")

x Values: 
tensor([[-1.5864, -0.2671,  2.6874],
        [-0.4633,  0.6639,  0.2383]])
y Values: 
tensor([-2.0497,  0.3969,  2.9257])
z Values: 
tensor([0.8339, 0.4390])


Indexing

In [35]:
x = torch.randn(2, 4)
print(
    f"X: \n{x}\n"
    f"x[:1]: \n{x[:1]}\n"
    f"x[:1, 1:3]: \n{x[:1, 1:3]}"
    )

X: 
tensor([[ 0.8305, -0.0838,  0.9523,  0.2016],
        [-0.1714, -0.8164, -0.6066, -0.4800]])
x[:1]: 
tensor([[ 0.8305, -0.0838,  0.9523,  0.2016]])
x[:1, 1:3]: 
tensor([[-0.0838,  0.9523]])


Slicing

In [38]:
# Select with dimensional indices
x = torch.randn(2, 3)
print(f"Values: \n{x}")

col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices)
print(f"Values: \n{chosen}")

row_indices = torch.LongTensor([0, 1])
col_indices = torch.LongTensor([0, 2])
chosen = x[row_indices, col_indices]
print(f"Values: \n{chosen}")

Values: 
tensor([[-0.4171, -2.3476,  1.9083],
        [-1.8304,  0.3223,  0.9229]])
Values: 
tensor([[-0.4171,  1.9083],
        [-1.8304,  0.9229]])
Values: 
tensor([-0.4171,  0.9229])


Joining

In [39]:
x = torch.randn(2, 3)
print (x)
print (x.shape)

tensor([[-0.0534, -0.3743,  0.0549],
        [ 0.3398, -1.3690,  0.5650]])
torch.Size([2, 3])


In [40]:
# Concatenation
y = torch.cat([x, x], dim=0)
print(y)
print(y.shape)

tensor([[-0.0534, -0.3743,  0.0549],
        [ 0.3398, -1.3690,  0.5650],
        [-0.0534, -0.3743,  0.0549],
        [ 0.3398, -1.3690,  0.5650]])
torch.Size([4, 3])


In [42]:
# stacking
z = torch.stack([x, x], dim=0)
print(z)
print(z.shape)

tensor([[[-0.0534, -0.3743,  0.0549],
         [ 0.3398, -1.3690,  0.5650]],

        [[-0.0534, -0.3743,  0.0549],
         [ 0.3398, -1.3690,  0.5650]]])
torch.Size([2, 2, 3])


Gradients

In [47]:
# Tensors with gradient bookkeeping
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z has to be a scalar
print (
    f"x: \n{x}\n"
    f"x.grad: \n{x.grad}"
)

x: 
tensor([[0.4472, 0.7964, 0.7277, 0.3657],
        [0.7023, 0.5396, 0.3144, 0.4608],
        [0.9706, 0.6502, 0.0872, 0.8186]], requires_grad=True)
x.grad: 
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


CUDA

In [51]:
# is CUDA available?
print (torch.cuda.is_available())

False


In [52]:
# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu
